; Limites de upload e memória
upload_max_filesize = 512M
post_max_size = 512M
memory_limit = 512M

session.cookie_secure = 1
session.cookie_httponly = 1
session.cookie_samesite = Lax
display_errors = Off
display_startup_errors = Off
expose_php = Off
